[ru]
t1 = "Привет, {name}. Этот бот будет следить за ценами на товары в Wildberries."
t2 = "Меню"
t3 = "Артикул товара:"
t4 = "Не похоже на артикул. Вот пример: 234335796\nПопробуй ещё раз :)"
t5 = "Поиск товара..."
t6 = "{emoji} Не найдено\nПопробуй ещё раз"
t7 = "{emoji} Найдено"
t8 = "<b>{name}</b>\nЦена на данный момент: <b>{price}</b> BYN\nПродолжить?"
t9 = "Отлично! Теперь укажи ожидаемую цену:"
t10 = "Хорошо, не добавляем"
t11 = "Не похоже на цену\nПопробуй ещё раз"
t12 = "Ожидаемая цена должна быть ниже текущей\nПопробуй ещё раз"
t13 = "{emoji} Добавлено"
t14 = "Пока пусто"
t15 = "{emoji1} {name}\n\n{emoji2} Нет в наличии"
t16 = "{emoji} {name}\nЦена: <b>{price}</b> BYN {price_symbol}\n<i>В наличии: {count} шт.</i>\n\nОжидаемая цена: <b>{desired_price}</b> BYN"
t17 = "Новая ожидаемая цена:"
t18 = "{emoji} Цена обновлена"
t19 = "{emoji} Удалено"
t20 = "{emoji} ЦЕНА СНИЗИЛАСЬ!\n{name}\n\n<b>{price}</b> BYN"
t21 = "Ожидаемая цена автоматически снижена на 5%\nНовая цена: <b>{price}</b> BYN"
t22 = "{emoji} В наличии всего: <b>{count}</b> шт.\n{name}\n\n<b>{price}</b> BYN"
t23 = "Язык"
t24 = "Установлен русский язык"

btn1 = "Отслеживаемые"
btn2 = "Добавить"
btn3 = "Отмена"
btn4 = "Да"
btn5 = "Нет"
btn6 = "Изменить цену"
btn7 = "Удалить"
btn8 = "Открыть на WB"
btn9 = "Настройки"

ph1 = "Артикул"
ph2 = "Продолжить?"
ph3 = "00.00"


[by]
t1 = "Прывітанне, {name}. Гэты бот будзе сачыць за цэнамі на тавары Wildberries."
t2 = "Меню"
t3 = "Артыкул тавару:"
t4 = "Не падобна на артыкул. Вось прыклад: 234335796\nПаспрабуй яшчэ раз :)"
t5 = "Пошук тавару..."
t6 = "{emoji} Не знойдзена\nПаспрабуй яшчэ раз"
t7 = "{emoji} Знойдзена"
t8 = "<b>{name}</b>\nЦана зараз: <b>{price}</b> BYN\nПрацягнуць?"
t9 = "Выдатна! Цяпер укажы чаканую цану:"
t10 = "Добра, не дадаем"
t11 = "Не падобна на цану\nПаспрабуй яшчэ раз"
t12 = "Чаканая цана павінна быць ніжэйшай за цяперашнюю\nПаспрабуй яшчэ раз"
t13 = "{emoji} Дададзена"
t14 = "Пакуль пуста"
t15 = "{emoji1} {name}\n\n{emoji2} Не ў наяўнасці"
t16 = "{emoji} {name}\nЦана: <b>{price}</b> BYN {price_symbol}\n<i>У наяўнасці: {count} шт.</i>\n\nЧаканая цана: <b>{desired_price}</b> BYN"
t17 = "Новая чаканая цана:"
t18 = "{emoji} Цана абноўлена"
t19 = "{emoji} Выдалена"
t20 = "{emoji} ЦАНА ЗНІЗІЛАСЯ!\n{name}\n\n<b>{price}</b> BYN"
t21 = "Чаканая цана аўтаматычна зніжана на 5%\nНовая цана: <b>{price}</b> BYN"
t22 = "{emoji} У наяўнасці ўсяго: <b>{count}</b> шт.\n{name}\n\n<b>{price}</b> BYN"
t23 = "Мова"
t24 = "Устаноўлена беларуская мова"

btn1 = "Мае тавары"
btn2 = "Дадаць"
btn3 = "Адмена"
btn4 = "Так"
btn5 = "Не"
btn6 = "Змяніць цану"
btn7 = "Выдаліць"
btn8 = "Адкрыць на WB"
btn9 = "Налады"

ph1 = "Артыкул"
ph2 = "Працягнуць?"
ph3 = "00.00"
